import { motion } from "motion/react";
import { TrendingUp, Zap, Shield, Activity, AlertTriangle, Database, CheckCircle, Wifi, RefreshCw, Radio, Clock3, Target, ArrowUpRight, ArrowDownRight } from "lucide-react";
import { Card3D } from "../components/inspira/Card3D";
import { GradientButton } from "../components/inspira/Buttons";
import { SparklesText } from "../components/inspira/SparklesText";
import { TextGenerateEffect } from "../components/inspira/TextGenerateEffect";
import { BorderBeam } from "../components/inspira/BorderBeam";
import { useWorkbench } from "../context/WorkbenchContext";
import { displayTeamTitle, formatRuleName, spriteUrl } from "../lib/api";

function StatCard({ label, value, detail, icon: Icon, color }: { label: string; value: string; detail?: string; icon: typeof Zap; color: string }) {
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
    <div className="flex items-start justify-between mb-3"><div className="w-9 h-9 rounded-lg flex items-center justify-center" style={{ background: color + "15" }}><Icon className="w-4.5 h-4.5" style={{ color }} /></div>{detail && <span className="text-xs font-medium text-slate-400">{detail}</span>}</div>
    <div className="text-2xl font-bold text-slate-800" style={{ fontFamily: "Rajdhani, sans-serif" }}>{value}</div><div className="text-xs text-slate-500 mt-0.5">{label}</div>
  </motion.div>;
}

function SignalBar({ label, value, tone = "#6366f1" }: { label: string; value: number; tone?: string }) {
  return <div className="space-y-1.5"><div className="flex items-center justify-between text-[11px] text-slate-500"><span>{label}</span><b className="font-mono font-medium text-slate-700">{value}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} transition={{ duration: .7 }} className="h-full rounded-full" style={{ background: tone }} /></div></div>;
}

function StatusDot({ active }: { active: boolean }) {
  return <span className={`inline-block h-2 w-2 rounded-full ${active ? "bg-emerald-500 animate-pulse" : "bg-slate-300"}`} />;
}

export function Dashboard() {
  const { team, registry, agent, replays, models, ratings, refresh } = useWorkbench();
  const activeRule = registry.active?.find((item: any) => item.battleType === (agent?.battleType || "double")) || registry.active?.find((item: any) => item.battleType === "double") || registry.active?.[0];
  const scoped = activeRule ? replays.filter((item: any) => item.rulesetId === activeRule.rulesetId || item.showdownFormatId === activeRule.showdownFormatId) : replays;
  const games = scoped.reduce((sum: number, item: any) => sum + Number(item.games || 0), 0);
  const wins = scoped.reduce((sum: number, item: any) => sum + Number(item.wins || 0), 0);
  const losses = scoped.reduce((sum: number, item: any) => sum + Number(item.losses || 0), 0);
  const winRate = games ? `${((wins / games) * 100).toFixed(1)}%` : "--";
  const running = ["STARTING", "CONNECTING", "AUTHENTICATED", "SEARCHING", "BATTLE", "RUNNING"].includes(agent?.status);
  const registryModel = models.find((item: any) => item.rulesetId === activeRule?.rulesetId);
  const currentRating = ratings.find((item: any) => item.rulesetId === activeRule?.rulesetId && item.showdownFormatId === activeRule?.showdownFormatId);
  const ratingValue = currentRating?.rating ?? (agent?.ratingRulesetId === activeRule?.rulesetId && agent?.ratingShowdownFormatId === activeRule?.showdownFormatId ? agent?.rating : null);
  const ratingDetail = currentRating?.updatedAt || agent?.ratingUpdatedAt ? `同步于 ${new Date(currentRating?.updatedAt || agent?.ratingUpdatedAt).toLocaleString()}` : "尚未收到官方分数";
  const champion = registryModel?.champion?.version || agent?.policyVersion || "尚未建立";
  const displayTeam = (running && agent?.submittedTeam?.length ? agent.submittedTeam : team).map((member: any, index: number) => {
    const local = team.find((item: any) => item.id === member.id || item.name === member.name);
    return { ...local, ...member, localizedName: local?.localizedName || member.name, sprite: local?.sprite || member.sprite || member.id, role: local?.role || "排位配置", types: local?.types || [] };
  });
  const moves = team.flatMap((member: any) => member.moves || []).map((move: string) => move.toLowerCase().replace(/[^a-z0-9]/g, ""));
  const count = (names: string[]) => moves.filter((move: string) => names.includes(move)).length;
  const coverage = [{ label: "输出", v: Math.min(100, count(["electroshot", "wavecrash", "earthpower", "sludgebomb"]) * 16 + 35) }, { label: "耐久", v: Math.min(100, count(["protect", "leechseed", "ragepowder"]) * 15 + 35) }, { label: "速度", v: Math.min(100, count(["tailwind", "trickroom", "aquajet"]) * 18 + 35) }, { label: "轮转", v: Math.min(100, count(["fakeout", "partingshot", "flipturn"]) * 18 + 35) }];
  const roleCounts = displayTeam.reduce((counts: Record<string, number>, member: any) => {
    const role = String(member.role || "排位配置").split(/[ /·]/)[0] || "排位配置";
    counts[role] = (counts[role] || 0) + 1;
    return counts;
  }, {});
  const recentBattles = scoped.flatMap((batch: any) => (batch.replays?.length ? batch.replays.map((replay: any) => ({ ...replay, batchId: batch.batchId, policyVersion: replay.policyVersion || batch.policyVersion, teamTitle: replay.teamTitle || batch.teamTitle || batch.teamSource })) : [{ ...batch, replayId: batch.batchId }])).slice(0, 6);
  const actionLabel = agent?.lastRequestSummary || agent?.queueStatus || (running ? "等待 Showdown 请求" : "等待启动排位");
  const sessionWins = Number(agent?.sessionWins || wins);
  const sessionLosses = Number(agent?.sessionLosses || losses);

  return <div className="space-y-6">
    <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold text-white mb-1" style={{ fontFamily: "Rajdhani, sans-serif" }}><SparklesText sparkleColor="#a78bfa" count={5}><TextGenerateEffect text="Champion Forge" speed={50} /></SparklesText></h1><p className="text-slate-400 text-sm">竞技宝可梦战术工作台 · 总览面板</p></div><div className="flex items-center gap-3"><div className={`flex items-center gap-2 px-3 py-1.5 rounded-full border text-xs ${running ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400" : "bg-slate-500/10 border-slate-500/20 text-slate-400"}`}><span className={`w-1.5 h-1.5 rounded-full ${running ? "bg-emerald-400 animate-pulse" : "bg-slate-400"}`} />Agent {running ? "运行中" : "已暂停"}</div><GradientButton onClick={() => refresh().catch(() => undefined)}><RefreshCw className="w-3.5 h-3.5" />刷新数据</GradientButton></div></motion.div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="当前天梯分" value={ratingValue == null ? "尚未获取" : String(ratingValue)} detail={ratingValue == null ? ratingDetail : `${currentRating?.ratingChange > 0 ? "+" : ""}${currentRating?.ratingChange ?? agent?.ratingChange ?? 0} 变化`} icon={TrendingUp} color="#4f46e5" /><StatCard label="相同规则胜率" value={winRate} detail={`${wins}胜 ${losses}负`} icon={Activity} color="#10b981" /><StatCard label="真实对局数" value={String(games)} detail={`${scoped.length} 批次`} icon={Shield} color="#7c3aed" /><StatCard label="当前进度" value={`${agent?.gamesFinished || 0}/${agent?.gamesRequested || 0}`} detail={agent?.status || "--"} icon={Zap} color="#f59e0b" /></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 items-stretch"><div className="lg:col-span-2 space-y-5"><BorderBeam active={running} color="indigo" duration={5}><div className="bg-white rounded-xl p-5"><div className="flex items-center justify-between mb-4"><h3 className="font-semibold text-slate-700 text-sm">当前排位队伍 <span className="text-slate-400 font-normal">{activeRule?.regulation || "等待规则"}</span></h3><span className="text-xs font-mono text-indigo-500">{agent?.teamTitle || agent?.teamSource || "workbench"}</span></div><div className="grid grid-cols-3 sm:grid-cols-6 gap-3">{displayTeam.slice(0, 6).map((poke: any, i: number) => <Card3D key={`${poke.id}-${i}`} intensity={6} className="group"><motion.div initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i * .05 }} className="bg-slate-50 rounded-lg p-2 text-center border border-slate-100 group-hover:border-indigo-200 transition-colors"><div className="w-14 h-14 mx-auto"><img src={spriteUrl(poke.sprite)} alt={poke.localizedName || poke.name} className="w-full h-full object-contain drop-shadow-sm" /></div><div className="text-xs font-medium text-slate-700 mt-1 leading-tight truncate">{poke.localizedName || poke.name}</div><div className="text-[10px] text-slate-400 truncate">{poke.role || poke.item || "排位配置"}</div></motion.div></Card3D>)}</div><div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-3">{coverage.map((s) => <SignalBar key={s.label} label={s.label} value={s.v} />)}</div></div></BorderBeam>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <section className="bg-white rounded-xl border border-slate-100 shadow-sm p-5 min-h-52"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Radio className="w-4 h-4 text-indigo-500" /><h3 className="font-semibold text-slate-700 text-sm">战术遥测</h3></div><span className="flex items-center gap-1.5 text-[10px] text-slate-400"><StatusDot active={running} />{running ? "实时" : "待机"}</span></div><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] text-slate-400">当前操作</div><div className="mt-1 truncate text-sm font-semibold text-slate-700" title={String(actionLabel)}>{actionLabel}</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] text-slate-400">本次会话</div><div className="mt-1 text-sm font-semibold text-slate-700">{sessionWins}胜 {sessionLosses}负</div></div></div><div className="mt-4 space-y-2 text-xs"><div className="flex justify-between text-slate-500"><span>队伍来源</span><b className="max-w-40 truncate font-medium text-slate-700">{agent?.teamTitle || agent?.teamSource || "配队工坊"}</b></div><div className="flex justify-between text-slate-500"><span>策略</span><b className="max-w-40 truncate font-mono font-medium text-slate-700">{agent?.policyVersion || champion}</b></div></div></section>
        <section className="bg-white rounded-xl border border-slate-100 shadow-sm p-5 min-h-52"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Target className="w-4 h-4 text-violet-500" /><h3 className="font-semibold text-slate-700 text-sm">阵容结构</h3></div><span className="text-[10px] text-slate-400">前端分析</span></div><div className="space-y-3">{Object.entries(roleCounts).length ? Object.entries(roleCounts).slice(0, 4).map(([role, value]) => <SignalBar key={role} label={`${role} · ${value}只`} value={Math.min(100, Number(value) * 24 + 16)} tone="#8b5cf6" />) : <div className="py-8 text-center text-xs text-slate-400">暂无队伍配置</div>}</div><div className="mt-4 flex flex-wrap gap-1.5">{coverage.map((s) => <span key={s.label} className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] text-indigo-600">{s.label} {s.v}</span>)}</div></section>
      </div>
      <section className="bg-white rounded-xl border border-slate-100 shadow-sm p-5 min-h-52"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Clock3 className="w-4 h-4 text-emerald-500" /><h3 className="font-semibold text-slate-700 text-sm">最近对局时间线</h3></div><span className="text-[10px] text-slate-400">{recentBattles.length} 条记录</span></div>{recentBattles.length ? <div className="space-y-2.5">{recentBattles.slice(0, 4).map((item: any, index: number) => { const won = Number(item.wins || 0) > Number(item.losses || 0) || item.result === "win"; return <div key={`${item.batchId || item.replayId}-${index}`} className="flex items-center gap-3 rounded-lg bg-slate-50 px-3 py-2.5"><span className={`h-2 w-2 shrink-0 rounded-full ${won ? "bg-emerald-500" : "bg-rose-400"}`} /><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-700">{item.teamTitle || item.teamSource || item.policyVersion || "真实对局"}</div><div className="mt-0.5 truncate text-[10px] text-slate-400">{item.policyVersion || "--"} · {item.finishedAt ? new Date(item.finishedAt).toLocaleString("zh-CN", { hour12: false }) : "暂无时间"}</div></div><div className={`flex items-center gap-1 text-xs font-semibold ${won ? "text-emerald-600" : "text-rose-500"}`}>{won ? <ArrowUpRight className="w-3.5 h-3.5" /> : <ArrowDownRight className="w-3.5 h-3.5" />}{item.result ? (won ? "胜" : "负") : `${item.wins || 0}-${item.losses || 0}`}</div></div>; })}</div> : <div className="py-8 text-center text-xs text-slate-400">暂无相同规则的真实对局记录</div>}</section>
    </div>
      <div className="space-y-4"><div className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm"><h3 className="text-xs font-semibold text-slate-500 uppercase mb-3">Agent 状态</h3><div className="space-y-2.5">{[["在线状态", running ? "在线" : "已暂停"], ["当前操作", agent?.lastRequestSummary || agent?.queueStatus || "等待启动"], ["使用模型", champion], ["策略版本", agent?.policyVersion || "--"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{label}</span><span className="text-xs font-medium text-slate-700 truncate max-w-44" title={String(value)}>{value}</span></div>)}</div></div>
        <div className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm"><div className="flex items-center justify-between mb-3"><h3 className="text-xs font-semibold text-slate-500 uppercase">规则快照</h3>{registry.canOperate ? <span className="flex items-center gap-1 text-[10px] text-emerald-500"><CheckCircle className="w-3 h-3" />正常</span> : <span className="flex items-center gap-1 text-[10px] text-red-500"><AlertTriangle className="w-3 h-3" />规则漂移</span>}</div><div className="space-y-1.5">{[["规则集", formatRuleName(activeRule?.name || "--")], ["Regulation", activeRule?.regulation || "--"], ["格式 ID", activeRule?.showdownFormatId || "--"], ["规则哈希", activeRule?.formatHash ? `#${activeRule.formatHash.slice(0, 8)}` : "--"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3"><span className="text-xs text-slate-400">{label}</span><span className="text-xs font-mono font-medium text-slate-600 truncate max-w-48" title={value}>{value}</span></div>)}</div></div>
        <div className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm"><h3 className="text-xs font-semibold text-slate-500 uppercase mb-3">数据采集</h3><div className="flex items-center gap-2 mb-2"><Database className="w-3.5 h-3.5 text-indigo-400" /><span className="text-xs text-slate-600">真实回放</span><span className="ml-auto text-xs font-mono text-indigo-500">{games} 局</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${Math.min(100, games / 2)}%` }} /></div><div className="text-[10px] text-slate-400 mt-1">训练窗口 200 局 · {Math.min(100, Math.round(games / 2))}%</div></div></div></div>
    <div className="bg-white rounded-xl overflow-hidden border border-slate-100 shadow-sm"><div className="px-5 py-3.5 border-b border-slate-100 flex items-center justify-between"><h3 className="font-semibold text-slate-700 text-sm">最近真实批次</h3><Wifi className="w-3.5 h-3.5 text-emerald-400" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50">{["批次", "策略", "结果", "队伍来源", "回放", "时间"].map((h) => <th key={h} className="px-4 py-2.5 text-left text-xs font-semibold text-slate-400 whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-50">{scoped.slice(0, 8).map((item: any) => <tr key={item.batchId} className="hover:bg-indigo-50/30"><td className="px-4 py-3 font-mono text-xs text-slate-400">{item.batchId}</td><td className="px-4 py-3 text-slate-700">{item.policyVersion || "--"}</td><td className="px-4 py-3"><span className={`px-2 py-.5 rounded-full text-xs font-semibold ${item.wins >= item.losses ? "bg-emerald-50 text-emerald-600" : "bg-red-50 text-red-500"}`}>{item.wins}胜 {item.losses}负</span></td><td className="px-4 py-3 text-slate-500 text-xs">{item.teamTitle || item.teamSource || item.teamVersion}</td><td className="px-4 py-3 text-slate-500 text-xs">{item.replayCount || item.replays?.length || 0}</td><td className="px-4 py-3 text-slate-400 text-xs whitespace-nowrap">{item.finishedAt ? new Date(item.finishedAt).toLocaleString() : "--"}</td></tr>)}{!scoped.length && <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-400">暂无相同规则的真实对局记录</td></tr>}</tbody></table></div></div>
  </div>;
}
