import { useState } from "react";
import { motion } from "motion/react";
import { BookOpen, CheckCircle, AlertTriangle, RefreshCw, ChevronDown, ChevronUp } from "lucide-react";
import { InteractiveHoverButton } from "../components/inspira/Buttons";
import { BorderBeam } from "../components/inspira/BorderBeam";
import { useWorkbench } from "../context/WorkbenchContext";
import { formatRuleName } from "../lib/api";

export function Rules() {
  const { registry, history, syncRules } = useWorkbench();
  const [syncing, setSyncing] = useState(false);
  const [showHistory, setShowHistory] = useState(true);
  const sync = async () => { setSyncing(true); try { await syncRules(); } finally { setSyncing(false); } };
  const drift = registry.status !== "ACTIVE" || !registry.canOperate;
  return <div className="space-y-5"><motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-white" style={{ fontFamily: "Rajdhani, sans-serif" }}>规则与环境</h1><p className="text-slate-400 text-sm mt-.5">在线格式、本地 Showdown 与合法池的真实快照</p></div><InteractiveHoverButton onClick={sync} disabled={syncing}><RefreshCw className={`w-3.5 h-3.5 ${syncing ? "animate-spin" : ""}`} />{syncing ? "同步中" : "同步规则"}</InteractiveHoverButton></motion.div>
    <div className={`rounded-xl p-4 border flex items-start gap-3 ${drift ? "bg-red-50 border-red-100" : "bg-emerald-50 border-emerald-100"}`}>{drift ? <AlertTriangle className="w-5 h-5 text-red-500" /> : <CheckCircle className="w-5 h-5 text-emerald-500" />}<div><div className={`font-semibold ${drift ? "text-red-700" : "text-emerald-700"}`}>{drift ? `规则状态：${registry.status}` : "规则快照已同步"}</div><div className={`text-sm mt-.5 ${drift ? "text-red-600" : "text-emerald-600"}`}>{drift ? "配队与排位已被阻止，请先同步规则。" : "本地引擎与当前官方 Champions 格式一致。"}</div></div></div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">{(registry.active || []).map((rule: any) => <BorderBeam key={rule.rulesetId} active={syncing} color={rule.battleType === "double" ? "indigo" : "cyan"} duration={3}><div className="bg-white rounded-xl p-5"><div className="flex items-start justify-between gap-3 mb-5"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center"><BookOpen className="w-5 h-5 text-indigo-500" /></div><div><div className="font-bold text-slate-800 text-lg">{formatRuleName(rule.name)}</div><div className="text-sm text-emerald-600 mt-.5">{rule.battleType === "double" ? "VGC 双打" : "BSS 单打"} · 当前生效</div></div></div><div className="font-mono text-xs text-indigo-600">#{rule.formatHash?.slice(0, 8)}</div></div><div className="grid grid-cols-2 gap-3">{[["规则集 ID", rule.rulesetId], ["Showdown 格式", rule.showdownFormatId], ["Regulation", rule.regulation], ["排位状态", rule.rated ? "Rated" : "未开放"], ["规则哈希", rule.formatHash?.slice(0, 16)], ["合法池哈希", rule.legalPoolHash?.slice(0, 16)], ["Showdown Commit", rule.showdownCommit?.slice(0, 12)], ["开放搜索", rule.searchShow ? "是" : "否"]].map(([label, value]) => <div key={label} className="bg-slate-50 rounded-lg p-3 min-w-0"><div className="text-[10px] text-slate-400 mb-1">{label}</div><div className="text-sm font-medium text-slate-700 font-mono truncate" title={value}>{value || "--"}</div></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{(rule.rules || []).map((item: string) => <span key={item} className="px-2.5 py-1 rounded-full bg-indigo-50 text-indigo-600 text-xs">{item}</span>)}</div>{rule.banlist?.length ? <div className="mt-4 p-3 bg-red-50 rounded-lg text-xs text-red-600">Banlist: {rule.banlist.join("、")}</div> : null}</div></BorderBeam>)}</div>
    <div className="bg-white rounded-xl overflow-hidden border border-slate-100 shadow-sm"><button onClick={() => setShowHistory(!showHistory)} className="w-full px-5 py-3.5 flex items-center justify-between hover:bg-slate-50"><h3 className="text-sm font-semibold text-slate-700">历史规则快照</h3>{showHistory ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}</button>{showHistory && <div className="border-t border-slate-100">{history.map((rule: any, i: number) => <div key={`${rule.rulesetId}-${i}`} className="px-5 py-4 flex items-center gap-4 border-b border-slate-50 last:border-0"><div className={`w-2 h-2 rounded-full ${rule.status === "active" ? "bg-emerald-400" : "bg-slate-300"}`} /><div className="flex-1 min-w-0"><div className="font-medium text-slate-700 text-sm">{formatRuleName(rule.name)}</div><div className="text-xs text-slate-400 mt-.5 truncate">{rule.rulesetId} · {rule.regulation}</div></div><div className="text-right text-xs font-mono text-slate-400">#{rule.formatHash?.slice(0, 8)}<br />{rule.firstSeenAt ? new Date(rule.firstSeenAt).toLocaleString() : "--"}</div></div>)}</div>}</div>
    <div className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm"><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-semibold text-slate-700">规则漂移监控</h3><span className={`text-xs ${drift ? "text-red-500" : "text-emerald-500"}`}>{registry.status || "LOADING"}</span></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[["在线与本地", !drift, drift ? "不一致" : "一致"], ["规则差异", !(registry.differences || []).length, `${(registry.differences || []).length} 项`], ["最近同步", Boolean(registry.lastSyncAt), registry.lastSyncAt ? new Date(registry.lastSyncAt).toLocaleString() : "未同步"]].map(([label, ok, value]: any) => <div key={label} className={`rounded-lg p-3 border ${ok ? "bg-emerald-50 border-emerald-100" : "bg-red-50 border-red-100"}`}><div className="flex items-center gap-1.5">{ok ? <CheckCircle className="w-3.5 h-3.5 text-emerald-500" /> : <AlertTriangle className="w-3.5 h-3.5 text-red-500" />}<span className={`text-xs font-medium ${ok ? "text-emerald-700" : "text-red-700"}`}>{label}</span></div><div className="text-[10px] font-mono mt-1 text-slate-500">{value}</div></div>)}</div></div></div>;
}
